# Generated by Django 4.2.7 on 2023-11-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='c_img',
            field=models.ImageField(null=True, upload_to='Country'),
        ),
    ]
