# Generated by Django 4.2.7 on 2023-11-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0002_country_c_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='c_img',
            field=models.ImageField(blank=True, null=True, upload_to='Country'),
        ),
    ]
