# Generated by Django 4.2.7 on 2023-11-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0003_alter_country_c_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='c_img',
            new_name='img',
        ),
    ]
