# Generated by Django 4.2.7 on 2023-11-15 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0004_rename_c_img_country_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
    ]
