# Generated by Django 4.2.7 on 2023-11-15 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0005_remove_country_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='League_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccergames.country')),
            ],
        ),
    ]
