# Generated by Django 4.2.7 on 2023-11-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0006_league_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='League_country',
            new_name='League',
        ),
    ]
