# Generated by Django 4.2.7 on 2023-11-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0007_rename_league_country_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='country',
            new_name='l_country',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
