# Generated by Django 4.2.7 on 2023-11-16 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soccergames', '0011_alter_country_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
