# Generated by Django 4.2.7 on 2023-11-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0012_country_client_alter_country_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='client',
        ),
    ]
