# Generated by Django 4.2.7 on 2023-11-16 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccergames', '0015_alter_league_l_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('last_games', models.CharField(choices=[('W', 'WIN'), ('D', 'DRAW'), ('L', 'LOSE')], max_length=5)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_odd', models.FloatField()),
                ('draw_odd', models.FloatField()),
                ('away_odd', models.FloatField()),
                ('goals', models.CharField(max_length=1)),
                ('result', models.BooleanField(default=False)),
                ('g_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccergames.country')),
                ('g_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soccergames.league')),
            ],
        ),
    ]
